import numpy as np
Zero=np.array(10)
print(Zero)
print(type(Zero))
print(Zero.ndim)
print(Zero.nbytes)
One=np.array([12,24,36,48,60])
print(One)
Two=np.array([[1,2,4],[5,6,7]])
print(Two)
Three=np.array([[[1,2,3],[5,6,7]],[[12,23,34],[13,43,23]]])
print(Three)
print("Dimension :",One.ndim)
print("Memory: ",One.nbytes)
print("Dimension: ",Two.ndim)
print("Memory: ",Two.nbytes)
print("Dimension: ",Three.ndim)
print("Memory: ",Three.nbytes)
a=np.array([1,2,3,4,5])
z=np.zeros(5)
o=np.ones((2,3))
r=np.arange(0,10,2)
l=np.arange(0,1,5)
rd=np.random.randint(1,100,6)
print(a,z,o,r,l,rd)